export { default as Banner } from './Banner'
export { default as About } from './About'
export { default as Brand } from './Brand'
export { default as Services } from './Services'
export { default as Projects } from './Projects'
export { default as Skills } from './Skills'
export { default as Contact } from './Contact'
export { default as FeaturedPost } from './FeaturedPost'
